### PR TITLE
Remove gulp and build task

### PR DESCRIPTION
**Pull request by AmrAbdulrahman**

### CODE REVIEW

**Comment by baruchvlz** [comment]
Note that this is a breaking change as the location of the files will change from `dist` to `src`. Any project using RC2 + or updating to RC2+ should be weary of this.

I will update the `CHANGELOG` and the `.npmignore` files accordingly.

**Comment by TejasQ** [comment]
But if you point your `main` in `package.json` to `src`, that'll effectively make it a non-breaking change, right?

**Comment by baruchvlz** [comment]
@TejasQ Unless you're trying to import directly from a component folder.

For example:  `~mcmakler-components-react/dist/components/RadioButton` will break with these changes.

Not saying this is correct or that we do it this way, but it could still happen.

**Comment by TejasQ** [comment]
You're right. It's just a bit of a strange pattern for me to import something from the internals of a library.

**Comment by saibs** [comment]
LGTM

**Pull request merged**
