### PR TITLE
chore(header) default props has been updated

### PR DESCRIPTION
**Pull request by abpolat**

### CODE REVIEW

**Comment by baruchvlz** [comment]
Why do we have all these default props? The idea of this is to be decoupled from any logic, but having these hard coded values doesn't allow this.

In any case, it's up to @saibs

**Comment by abpolat** [comment]
> Why do we have all these default props? The idea of this is to be decoupled from any business logic, but having these hard coded values doesn't allow this.
> 
> In any case, it's up to @saibs

That is only for landing pages, so you can just import the header and use it without passing anything. On the main site, these are already setting by config.

**Comment by TejasQ** [comment]
USE TYPESCRIPT

**Comment by baruchvlz** [comment]
My mistake.

**Pull request merged**
