### PR TITLE
Use Gulp to build library

### PR DESCRIPTION
**Pull request by baruchvlz**
- Use Gulp to transpile ES6 & SCSS
- Adjust storybook to import SCSS files from src
- remove nwb dependency

Todo:

- [ ] Verify lib import in NextJS project
- [ ] Verify lib import in React project

### CODE REVIEW

**Comment by saibs** [comment]
If we do this, then projects using webpack can never include component that includes scss?

Would it not be better if keep the nwb as it is, and add the gulp script, so that our npm package is compatible with webpack and use in node_modules without transpilation?

I guess you will have problem with '~' in scss

**Comment by TejasQ** [comment]
This is interesting! Why `gulp` as a build tool?

**Comment by saibs** [comment]
The problem is we are not able to use non-transpiled components in nextjs, because of this high priority issue:
https://github.com/zeit/next.js/issues/706

**Comment by baruchvlz** [comment]
@saibs That makes sense, thing is NWB also creates a `lib` folder which is the same as the one from gulp. So we can either re-write the `lib` folder or create a new one `dist` which includes the gulp generated files for NextJS.

```
package.json
LICENSE
lib/
dist/
```

**Pull request closed without merging**
